BINS=oscilloscope.elf
OBJS=./avr_common/uart.o ./adc/adc.o ./voltage_switch/voltage_switch.o ./square_wave/square_wave.o
HEADERS=./avr_common/uart.h ./adc/adc.h ./voltage_switch/voltage_switch.h ./square_wave/square_wave.h

include ./avr_common/avr.mk
